# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of Kvadrat
# !-----------------------------------------------------------------------------------------------!
#
#    This is the main plugin's settings class. You can use SimpleSettings to load values from it,
#    and update it automatically.
#
#    For support and documentation, please visit:
#    - https://github.com/AnleaR/Kvadrat/wiki
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/AnleaR/Kvadrat/wiki/Use-Right-Encoding
#
#    4) JSON is supported.
#       - For usage, see https://github.com/AnleaR/Kvadrat/wiki/JSON
#
#    5) WHITELISTS can be turned into blacklists, by putting "@blacklist" on the first line.
#       - Doing such, filters will only apply for messages in those lists.
#
#    PS: Everything above applies for all files in Kvadrat/ folder.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Example of a section
# -------------------------------------------------------------------------------------------------
Example:

  # An example of a config key
  Sample_Flag: true

# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp} and {location} variables. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
#
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [template]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied 
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&cKvadrat&8]&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. You can also use the LagCatcher class to invoke
# this feature. We log a console message if an operation takes over the time below (milliseconds). 
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: []

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# NB: Don't forget to keep this up-to-date with the getConfigVersion method in your Settings class. 
# -------------------------------------------------------------------------------------------------
Version: 1

General:
  WeekDays: [ "пн", "вт", "ср", "чт", "пт", "сб", "вс" ]
  Times: [ "12:00", "20:00" ]
  # In Seconds
  EventTime: 300
  # <c>кликабельное сообщение</c> - при клике вызовет команду /kvad (можно использовать только 1 в строке)
  StartMessages:
    - "&8&l ============================="
    - "&6 Начинается событие &9&lКвадрат &6для участия тыкните &b<c>сюда</c> &6или введите команду &b/kvad"
    - "&8&l ============================="
  # How often the payment for zone will be given
  PaymentTicks: 60
  # How often will be check player's status for bossbar
  BossbarChangeTicks: 20
  MoneyForPvpZone: 25
  MoneyForChestZone: 50
  PercentForKill: 25
  # Сколько сек. можно бить чела, если он из сейв зоны забежал в пвп и обратно
  PvpSecondsAfterSafeZone: 15
  # Сколько сек. можно бить чела, если он кликал и убежал в сейв зону
  PvpSecondsAfterClicks: 20
  # In seconds
  KvadCooldown: 20
  # When plugin will broadcast how much time lasts
  AlertSeconds: [ 240, 180, 120, 60, 30, 15, 5, 4, 3, 2, 1]
  # Призы на все места в эндер-рублях, если не будет столько участников, сколько призовых мест - приз просто не дастся никому.
  Prizes:
    1: 50
  PvpAllowedCmds:
    - "spawn"
    - "warp"

SmallLocation:
  MinOnline: 20
  # БЕРИТЕ ЗОНЫ С ЗАПАСОМ, ЧТОБ ТОЧНО НЕ ГРИФЕРИЛИ
  World: "world"
  # Teleport on /kvad
  Spawns:
    1:
      X: -252.5
      Y: 126.0
      Z: 202.5
      Yaw: -90.0
      Pitch: 0.0
    2:
      X: -237.5
      Y: 126.0
      Z: 202.5
      Yaw: -90.0
      Pitch: 0.0
  # Where is the dispenser with clicker
  Dispenser:
    X: -245
    Y: 126
    Z: 202
  # Zones from block A to block B (like region in WG)
  SafeZoneA:
    X: -236
    Y: 125
    Z: 193
  SafeZoneB:
    X: -254
    Y: 255
    Z: 211
  PvpZoneA:
    X: -241
    Y: 125
    Z: 198
  PvpZoneB:
    X: -249
    Y: 255
    Z: 206
  ChestZoneA:
    X: -244
    Y: 125
    Z: 201
  ChestZoneB:
    X: -246
    Y: 255
    Z: 203

BigLocation:
  MinOnline: 50
  # БЕРИТЕ ЗОНЫ С ЗАПАСОМ, ЧТОБ ТОЧНО НЕ ГРИФЕРИЛИ
  World: "world"
  # Teleport on /kvad
  Spawns:
    1:
      X: -252.5
      Y: 126.0
      Z: 202.5
      Yaw: -90.0
      Pitch: 0.0
    2:
      X: -237.5
      Y: 126.0
      Z: 202.5
      Yaw: -90.0
      Pitch: 0.0
  # Where is the dispenser with clicker
  Dispenser:
    X: -245
    Y: 126
    Z: 202
  # Zones from block A to block B (like region in WG)
  SafeZoneA:
    X: -236
    Y: 125
    Z: 193
  SafeZoneB:
    X: -254
    Y: 255
    Z: 211
  PvpZoneA:
    X: -241
    Y: 125
    Z: 198
  PvpZoneB:
    X: -249
    Y: 255
    Z: 206
  ChestZoneA:
    X: -244
    Y: 125
    Z: 201
  ChestZoneB:
    X: -246
    Y: 255
    Z: 203

Spawn:
  World: "world"
  X: -258.5
  Y: 126.0
  Z: 202.5
  Yaw: -90.0
  Pitch: 0.0

Menu:
  Title: "&6Квадрат"
  Button:
    Material: SUNFLOWER
    Name: "&6Кликни на меня"
    Lore:
      - "&eКликай сюда, чтоб получать очки"
      - "&eПобедит тот, кто больше накликает"
      - "&eАккуратнее со мной, я могу убегать :)"

Scoreboard:
  Title: "&9&lКвадрат"
  # Placeholders:
  # (player) - player's name
  # (place) - player's place
  # (clicks) - player's clicks count
  # (myplace) - place of player
  RowFormat: "&6(place). &e(player) &7- &e(clicks) &7клик."
  Places: 10

Bossbar:
  SafeZone:
    Title: "&aВы в безопасной зоне"
    Color: "GREEN"
    Style: "SOLID"
  PvpZone:
    Title: "&cОпасно, вы уязвимы"
    Color: "RED"
    Style: "SOLID"
  Timer:
    # (sec) - осталось секунд до неуязвимости
    Title: "&4Опасно, вы уязвимы ещё (sec) сек."
    Color: "RED"
    Style: "SOLID"

KvadratLocale:
  EVENT_NOT_STARTED_MIN_ONLINE:
    - "&8&l ============================="
    - "&9&lКвадрат &cне был запущен, тк на сервере слишком мало игроков"
    - "&8&l ============================="
  EVENT_NOT_STARTED: "&cКвадрат ещё не начался"
  NOT_IN_CHEST_ZONE: "&cВы должны находиться в 3 зоне, чтобы открыть раздатчик"
  NOT_CLICK_ALL: "&cНе кликай на всё подряд!"
  ON_HOVER_KVAD: "&7Кликни на меня, чтобы принять участие"
  # (perc) - процент из General
  WE_TOOK_PERCENT_CLICKS: "&cМы забрали у вас (perc)% кликов, тк вы умерли или покинули Квадрат"
  # (killed) - имя убитого игрока
  # (clicks) - процент из General
  GIVE_CLICKS_FOR_KILL: "&aВы получили (clicks) клик. за убийство (killed)"
  # (time) - форматированное максимальное время
  ALERT_FORMAT:
    - "&8&l ============================="
    - "&e Осталось &6(time) &eдо конца &9&lКвадрата"
    - "&8&l ============================="
  # (place_1), (place_2)... etc. - ники игроков, занявших места
  # (clicks_1), (clicks_2)... etc. - клики ироков, занявших места
  RESULT_FORMAT:
    - "&8&l ============================="
    - "&6 Итоги &9&lКвадрата"
    - "&e1. (place_1) &7- (clicks_1) &7кликов. Получает &e50 эндер-рублей"
    - "&8&l ============================="
  PVP_BLOCK_COMMAND: "&cВы не можете использовать команды в пвп-режиме"
  ActionBar:
    # (sum) - сумма денег, полученных за нахождение в зоне
    GOT_PVP_ZONE_MONEY: "&eВы получаете &6(sum)$ &eкаждые 3 секунды за нахождение в пвп-зоне"
    # (sum) - сумма денег, полученных за нахождение в зоне
    GOT_CHEST_ZONE_MONEY: "&cВы получаете &4(sum)$ &cкаждые 3 секунды за нахождение в зоне раздатчика"
    IN_SAFE_ZONE: "&aВы в безопасной зоне"